name: Wildfire Monitor Trigger

on:
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set Up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Execute Monitor Script
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
        run: python bot.py

      - name: Save Log Changes
        run: |
          git config --global user.name "cron-bot"
          git config --global user.email "cron-bot@users.noreply.github.com"
          git add known_fires.txt
          git diff-index --quiet HEAD || (git commit -m "Automated log update [skip ci]" && git pull --ff-only && git push)
